In [1]:
import pandas as pd
GloVe_df = pd.read_csv("GloVe.csv")
Comm_df = pd.read_csv("HN_community - Copy.csv")

In [2]:
Comm_df.head(2)

   user_id  modularity_class
0        0               775
1        6                 0

In [3]:
Comm_df['modularity_class'].value_counts(sort=True).nlargest(15)

0       29945
1227      533
1340      351
775       351
188       344
1351      279
613       183
1739      139
1459       95
1242       78
1709       76
1392       23
970        13
617         8
1127        8
Name: modularity_class, dtype: int64

In [4]:
Users_df = pd.merge(GloVe_df, Comm_df, on = "user_id", how = "inner") 
Users_df.head(2)

,user_id,hate,0_glove,1_glove,2_glove,3_glove,4_glove,5_glove,6_glove,7_glove,...,291_glove,292_glove,293_glove,294_glove,295_glove,296_glove,297_glove,298_glove,299_glove,modularity_class
0,0,normal,-0.071806,0.106978,-0.176602,-0.055014,0.080056,-0.039964,0.024863,-0.087665,...,0.022277,-0.061740,-0.108736,0.095297,0.014048,-0.079171,-0.064034,0.039573,0.121562,775
1,6,other,-0.065580,0.147344,-0.152149,-0.026615,0.047478,-0.050444,-0.017763,-0.069236,...,0.065958,-0.036553,-0.091797,0.094917,-0.036796,-0.088716,-0.062558,0.062685,0.118133,0

In [5]:
GloVe = Users_df[Users_df.columns[2:-1]].to_numpy()
GloVe.shape

(34497, 300)

In [6]:
from sklearn.cluster import SpectralClustering
import numpy as np

In [7]:
%%time
clustering = SpectralClustering(n_clusters=12,
        assign_labels="discretize",
        random_state=0).fit(GloVe)
Users_df['spectral'] = clustering.labels_

Wall time: 23min 46s

In [11]:
%%time
normalizeGloVe = GloVe / np.linalg.norm(GloVe)
print(normalizeGloVe)

[[-1.30581574e-04  1.94543839e-04 -3.21156811e-04 ... -1.16447378e-04
   7.19655156e-05  2.21064133e-04]
 [-1.19260386e-04  2.67951411e-04 -2.76688911e-04 ... -1.13764441e-04
   1.13994872e-04  2.14828471e-04]
 [-5.18081522e-05  2.51516878e-04 -2.21139167e-04 ... -1.03894246e-04
   7.37376164e-05  2.15137446e-04]
 ...
 [-7.58830846e-05  2.51488806e-04 -5.35132235e-05 ... -6.89976940e-05
  -2.95956273e-05  1.28252121e-04]
 [-6.61079367e-05  2.61929298e-04 -2.92506441e-04 ... -8.85653186e-05
   1.01242670e-04  1.54025667e-04]
 [-8.75138768e-05  2.15971194e-04  8.33470991e-05 ... -2.99079865e-05
  -8.98906502e-05  1.34722440e-04]]
Wall time: 37.8 s

In [12]:
%%time
clustering = SpectralClustering(n_clusters=12,
        assign_labels="discretize",
        random_state=0).fit(normalizeGloVe)
Users_df['normal_spectral'] = clustering.labels_

Wall time: 22min 25s

In [13]:
import winsound
duration = 5000  # milliseconds
freq = 440  # Hz
winsound.Beep(freq, duration)

In [14]:
Users_df

,user_id,hate,0_glove,1_glove,2_glove,3_glove,4_glove,5_glove,6_glove,7_glove,...,293_glove,294_glove,295_glove,296_glove,297_glove,298_glove,299_glove,modularity_class,spectral,normal_spectral
0,0,normal,-0.071806,0.106978,-0.176602,-0.055014,0.080056,-0.039964,0.024863,-0.087665,...,-0.108736,0.095297,0.014048,-0.079171,-0.064034,0.039573,0.121562,775,0,7
1,6,other,-0.065580,0.147344,-0.152149,-0.026615,0.047478,-0.050444,-0.017763,-0.069236,...,-0.091797,0.094917,-0.036796,-0.088716,-0.062558,0.062685,0.118133,0,0,7
2,7,other,-0.028489,0.138307,-0.121603,-0.039703,0.079320,-0.033732,0.003317,-0.079703,...,-0.069890,0.086256,-0.024214,-0.064788,-0.057131,0.040548,0.118302,0,0,4
3,12,other,-0.038831,0.129995,-0.031333,0.010532,0.086184,-0.060529,0.036354,-0.129217,...,-0.113064,0.100583,-0.053707,-0.030563,-0.014074,-0.035487,0.098736,0,0,10
4,14,other,-0.088331,0.128460,-0.069922,0.011715,0.047237,-0.045111,0.010369,-0.077945,...,-0.071514,0.093105,-0.048317,-0.024028,-0.038796,-0.000818,0.095012,0,0,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34492,100380,hateful,-0.076519,0.119216,-0.090964,0.009253,0.070197,-0.071825,0.000311,-0.047510,...,-0.098586,0.087736,0.012583,-0.034733,-0.044058,-0.012266,0.103631,775,0,9
34493,100381,other,-0.058525,0.135925,-0.037535,0.046996,0.093766,-0.096308,-0.000296,-0.032090,...,-0.079700,0.057477,-0.037915,-0.044164,-0.029799,-0.056733,0.108609,0,0,3
34494,100382,other,-0.041728,0.138292,-0.029427,0.002030,0.092320,-0.057140,0.045027,-0.116939,...,-0.107279,0.135280,-0.022714,-0.062393,-0.037941,-0.016274,0.070525,0,0,10
34495,100384,other,-0.036352,0.144033,-0.160847,-0.027072,0.083716,-0.050102,0.023898,-0.136060,...,-0.104729,0.103883,-0.035841,-0.071515,-0.048701,0.055673,0.084698,0,0,0
34496,100385,normal,-0.048123,0.118761,0.045832,0.009058,0.096339,-0.088251,0.034114,-0.147926,...,-0.098556,0.129818,-0.084126,-0.044665,-0.016446,-0.049430,0.074083,1429,0,5

In [15]:
Users_df['modularity_class'].value_counts(sort=True).nlargest(15)

0       29866
1227      532
775       351
1340      349
188       343
1351      278
613       183
1739      139
1459       94
1242       78
1709       75
1392       23
970        12
617         8
1127        8
Name: modularity_class, dtype: int64

In [16]:
Users_df['spectral'].value_counts(sort=True).nlargest(15)

0     34116
10      195
7        54
5        49
9        34
6        14
8        14
3         7
4         7
1         5
2         1
11        1
Name: spectral, dtype: int64

In [17]:
Users_df['normal_spectral'].value_counts(sort=True).nlargest(15)

0     6526
7     4958
6     4646
11    3317
4     2857
1     2750
8     2585
3     2503
9     2150
10    1343
5      454
2      408
Name: normal_spectral, dtype: int64

In [16]:
from numpy import unique
from numpy import where
from sklearn.datasets import make_classification
from sklearn.cluster import SpectralClustering
from matplotlib import pyplot

In [17]:
X, _ = make_classification(n_samples=1000, n_features=2, n_informative=2, n_redundant=0, n_clusters_per_class=1, random_state=4)

In [18]:
X

array([[ 1.22515974, -0.95173116],
       [ 1.01630365, -1.72517506],
       [ 0.33534004, -1.7248955 ],
       ...,
       [ 1.54270795, -0.05566478],
       [ 0.81664566, -1.2509187 ],
       [ 1.13782254, -1.26151957]])

In [ ]:

# define the model
model = SpectralClustering(n_clusters=2)
# fit model and predict clusters
yhat = model.fit_predict(X)
# retrieve unique clusters
clusters = unique(yhat)
# create scatter plot for samples from each cluster
for cluster in clusters:
	# get row indexes for samples with this cluster
	row_ix = where(yhat == cluster)
	# create scatter of these samples
	pyplot.scatter(X[row_ix, 0], X[row_ix, 1])
# show the plot
pyplot.show()